
== https://github.com/wasmerio/wasmer[Wasmer]

=== Installation

https://wasmer.io/[Official site]

[source,shell]
$ brew install wasmer

=== https://docs.wasmer.io/runtime/get-started[Get Started]

[source,shell]
$ wasmer run python/python -- -c "print(1+1)"


=== Run in https://docs.wasmer.io/javascript-sdk[Browser] - https://docs.wasmer.io/javascript-sdk[The Wasmer JavaScript SDK]

[source,shell]
$ npm install -S @wasmer/sdk

For any application using npm and vite we use the following setups.

[source,shell]
$ npm init -y
$ npm install --save @wasmer/sdk
$ npm install vite --save-dev

Add two lines to `package.json`

[source]
----
"scripts": {
    "dev": "vite",
    "build": "vite build",
}
----

Alternatively, you can use `jq` to add key value pairs.

[source,shell]
$ brew install jq
$ cat package.json | jq '.+{scripts:{test:.scripts.test, dev: "vite", build: "vite build"}}'


To solve cross-origin issue for Wasmer module loading, you need to install

* https://github.com/chaosprint/vite-plugin-cross-origin-isolation[Vite plugin for CORS]
+
[source,shell]
$ npm i -D vite-plugin-cross-origin-isolation

* and put `vite.config.js` in your npm project root.

[source,js]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/vite.config.js[]
----


See also:

* https://docs.wasmer.io/javascript-sdk/explainers/troubleshooting#sharedarraybuffer-and-cross-origin-isolation[Troubleshooting]
* https://vitejs.dev/config/[Vite config]

==== Example: Hello World from Wasmer

[source,ts]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/index.ts[]
----

[source,html]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/index.html[]
----


==== Example: Source Code Runner

[source,ts]
----
include::./2-Wasmer/2.3.2-SourceCodeRunner/index.ts[]
----

[source,html]
----
include::./2-Wasmer/2.3.2-SourceCodeRunner/index.html[]
----


=== Issues

The problem here is that wasm is not cached by the browser. The `python/python` gets downloaded each time user refreshes the page.