
== https://github.com/wasmerio/wasmer[Wasmer]

=== Installation

https://wasmer.io/[Official site]

[source,shell]
$ brew install wasmer

=== https://docs.wasmer.io/runtime/get-started[Get Started]

[source,shell]
$ wasmer run python/python -- -c "print(1+1)"


=== Run in https://docs.wasmer.io/javascript-sdk[Browser] - https://docs.wasmer.io/javascript-sdk[The Wasmer JavaScript SDK]

[source,shell]
$ npm install -S @wasmer/sdk

For any application using npm and vite we use the following setups.

[source,shell]
----
$ npm init -y
$ npm install --save @wasmer/sdk
$ npm install vite --save-dev
----

Add two lines to `package.json`

[source]
----
"scripts": {
    "dev": "vite",
    "build": "vite build",
}
----

Alternatively, you can use `jq` to add key value pairs.

[source,shell]
$ brew install jq
$ cat package.json | jq '.+{scripts:{test:.scripts.test, dev: "vite", build: "vite build"}}'


To solve cross-origin issue for Wasmer module loading, you need to install

* https://github.com/chaosprint/vite-plugin-cross-origin-isolation[Vite plugin for CORS]
+
[source,shell]
$ npm i -D vite-plugin-cross-origin-isolation

* and put `vite.config.js` in your npm project root.

[source,js]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/vite.config.js[]
----


See also:

* https://docs.wasmer.io/javascript-sdk/explainers/troubleshooting#sharedarraybuffer-and-cross-origin-isolation[Troubleshooting]
* https://vitejs.dev/config/[Vite config]

==== Example: Hello World from Wasmer

[source,ts]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/index.ts[]
----

[source,html]
----
include::./2-Wasmer/2.3.1-HelloWorldFromWasmer/index.html[]
----


==== Example: Source Code Runner

[source,ts]
----
include::./2-Wasmer/2.3.2-SourceCodeRunner/index.ts[]
----

[source,html]
----
include::./2-Wasmer/2.3.2-SourceCodeRunner/index.html[]
----

The problem here is that wasm is not cached by the browser. The `python/python` gets downloaded each time user refreshes the page.

==== Example: https://docs.wasmer.io/javascript-sdk/tutorials/run[Markdown Editor]

Check the https://github.com/wasmerio/wasmer-js/tree/main/examples/markdown-editor[full original source]

1. Build `markdown-renderer/target/wasm32-wasi/release/markdown-renderer.wasm`, there are two ways
* Install `cargo` in your host machine
+
Install https://www.rust-lang.org/tools/install[Rust]
+
Install https://rustwasm.github.io/docs/book/game-of-life/setup.html[WebAssembly requirements for Rust]
+
[source,shell]
----
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ cargo install wasm-pack
$ cargo install cargo-generate
----
+
[source.shell]
$ rustup target add wasm32-wasi # This is the key ...
+
[source,shell]
$ brew install rust # Havn't try this yet, maybe we can use this and don't need to install wasm-pack and cargo-generate

* Use a docker container
+
[source,dockerfile]
----
include::./2-Wasmer/2.3.3-MarkdownEditor/markdown-renderer/Dockerfile[]
----
+
[source,shell]
$ docker run -it --name to-compile-rust -v "$PWD":/usr/src/myapp -w /usr/src/myapp my-rust-wasm32-wasi-compiler cargo build --release --target=wasm32-wasi

2. Run the WebAssembly
+
[source,ts]
----
include::./2-Wasmer/2.3.3-MarkdownEditor/index.ts[lines=2..8]
----