
all:

download: simple.wasm
	curl -LO https://github.com/wasmerio/wasmer-python/raw/master/examples/appendices/simple.wasm

copy:
	cp ./CompileWasmFromRustSource/simple/target/wasm32-unknown-unknown/release/simple.wasm .
